import { createClientFromRequest } from 'npm:@base44/sdk@0.8.4';

Deno.serve(async (req) => {
  try {
    const base44 = createClientFromRequest(req);
    const user = await base44.auth.me();

    if (!user) {
      return Response.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const { period_start, period_end, location_ids } = await req.json();

    if (!period_start || !period_end) {
      return Response.json({ 
        error: 'Missing required fields: period_start, period_end' 
      }, { status: 400 });
    }

    const orgId = user.organization_id || user.id;

    // Get organization details
    const orgs = await base44.asServiceRole.entities.Organization.filter({ id: orgId });
    const org = orgs[0];

    // Get batches in period
    const allBatches = await base44.asServiceRole.entities.TipAllocationBatch.filter({
      organization_id: orgId
    });

    const periodBatches = allBatches.filter(b => {
      const batchDate = new Date(b.batch_date);
      const start = new Date(period_start);
      const end = new Date(period_end);
      const matchesDate = batchDate >= start && batchDate <= end;
      const matchesLocation = !location_ids || location_ids.length === 0 || location_ids.includes(b.location_id);
      return matchesDate && matchesLocation;
    });

    // Get allocation lines
    const allLines = await base44.asServiceRole.entities.TipAllocationLine.filter({
      organization_id: orgId
    });

    const relevantLines = allLines.filter(line => 
      periodBatches.some(b => b.id === line.allocation_batch_id)
    );

    // Get adjustments
    const allAdjustments = await base44.asServiceRole.entities.Adjustment.filter({
      organization_id: orgId
    });

    const relevantAdjustments = allAdjustments.filter(adj =>
      periodBatches.some(b => b.id === adj.allocation_batch_id)
    );

    // Get payments (for refunds)
    const allPayments = await base44.asServiceRole.entities.Payment.filter({
      organization_id: orgId
    });

    const periodPayments = allPayments.filter(p => {
      const paymentDate = new Date(p.payment_date);
      return paymentDate >= new Date(period_start) && paymentDate <= new Date(period_end);
    });

    const refunds = periodPayments.filter(p => p.status === 'refunded');

    // Get audit events
    const allAuditEvents = await base44.asServiceRole.entities.SystemAuditEvent.filter({
      organization_id: orgId,
      hmrc_relevant: true
    });

    const relevantAuditEvents = allAuditEvents.filter(e => {
      const eventDate = new Date(e.created_date);
      return eventDate >= new Date(period_start) && eventDate <= new Date(period_end);
    });

    // Get locations
    const locations = await base44.asServiceRole.entities.Location.filter({
      organization_id: orgId
    });

    const filteredLocations = location_ids && location_ids.length > 0
      ? locations.filter(l => location_ids.includes(l.id))
      : locations;

    // Get tip rule sets
    const tipRules = await base44.asServiceRole.entities.TipRuleSet.filter({
      organization_id: orgId
    });

    // Build HTML report
    const formatCurrency = (value) => `£${((value || 0) / 100).toFixed(2)}`;
    const formatDate = (date) => new Date(date).toLocaleDateString('en-GB');

    const html = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>HMRC Tip Allocation Audit Pack</title>
  <style>
    body { font-family: Arial, sans-serif; max-width: 1200px; margin: 40px auto; padding: 20px; }
    h1 { color: #1e3a8a; border-bottom: 3px solid #1e3a8a; padding-bottom: 10px; }
    h2 { color: #475569; border-bottom: 1px solid #cbd5e1; padding-bottom: 8px; margin-top: 30px; }
    table { width: 100%; border-collapse: collapse; margin: 20px 0; }
    th { background: #f1f5f9; text-align: left; padding: 12px; border-bottom: 2px solid #cbd5e1; }
    td { padding: 10px; border-bottom: 1px solid #e2e8f0; }
    .summary-box { background: #f8fafc; border-left: 4px solid #3b82f6; padding: 15px; margin: 20px 0; }
    .warning-box { background: #fef3c7; border-left: 4px solid #f59e0b; padding: 15px; margin: 20px 0; }
    .footer { margin-top: 50px; padding-top: 20px; border-top: 2px solid #cbd5e1; font-size: 12px; color: #64748b; }
  </style>
</head>
<body>
  <h1>HMRC Tip Allocation Audit Pack</h1>
  
  <div class="summary-box">
    <h3>Report Period</h3>
    <p><strong>From:</strong> ${formatDate(period_start)} <strong>To:</strong> ${formatDate(period_end)}</p>
    <p><strong>Generated:</strong> ${formatDate(new Date())}</p>
    <p><strong>Generated by:</strong> ${user.email}</p>
  </div>

  <h2>Organization Details</h2>
  <table>
    <tr><td><strong>Business Name:</strong></td><td>${org?.name || 'N/A'}</td></tr>
    <tr><td><strong>PAYE Reference:</strong></td><td>${org?.paye_reference || 'N/A'}</td></tr>
    <tr><td><strong>Accounts Office Reference:</strong></td><td>${org?.accounts_office_reference || 'N/A'}</td></tr>
  </table>

  <h2>Total Tips Received by Location</h2>
  <table>
    <thead>
      <tr>
        <th>Location</th>
        <th>Total Tips Received</th>
        <th>Batches</th>
        <th>Employees</th>
      </tr>
    </thead>
    <tbody>
      ${filteredLocations.map(loc => {
        const locBatches = periodBatches.filter(b => b.location_id === loc.id);
        const locTotal = locBatches.reduce((sum, b) => sum + (b.total_tips_collected || 0), 0);
        const locEmployees = new Set(
          relevantLines.filter(l => l.location_id === loc.id).map(l => l.employee_id)
        ).size;
        return `
          <tr>
            <td>${loc.name}</td>
            <td>${formatCurrency(locTotal)}</td>
            <td>${locBatches.length}</td>
            <td>${locEmployees}</td>
          </tr>
        `;
      }).join('')}
      <tr style="font-weight: bold; background: #f1f5f9;">
        <td>TOTAL</td>
        <td>${formatCurrency(periodBatches.reduce((sum, b) => sum + (b.total_tips_collected || 0), 0))}</td>
        <td>${periodBatches.length}</td>
        <td>${new Set(relevantLines.map(l => l.employee_id)).size}</td>
      </tr>
    </tbody>
  </table>

  <h2>Allocation Methods & Rule Versions</h2>
  <table>
    <thead>
      <tr>
        <th>Location</th>
        <th>Allocation Method</th>
        <th>Rule Version</th>
        <th>Effective From</th>
      </tr>
    </thead>
    <tbody>
      ${filteredLocations.map(loc => {
        const locBatch = periodBatches.find(b => b.location_id === loc.id);
        const ruleSet = locBatch ? tipRules.find(r => r.id === locBatch.tip_rule_set_id) : null;
        return `
          <tr>
            <td>${loc.name}</td>
            <td>${locBatch?.allocation_method || 'N/A'}</td>
            <td>${ruleSet?.version || 'N/A'}</td>
            <td>${ruleSet ? formatDate(ruleSet.effective_from) : 'N/A'}</td>
          </tr>
        `;
      }).join('')}
    </tbody>
  </table>

  <h2>Allocation Summary</h2>
  <table>
    <thead>
      <tr>
        <th>Batch Date</th>
        <th>Location</th>
        <th>Tips Collected</th>
        <th>Tips Allocated</th>
        <th>Employees</th>
        <th>Status</th>
      </tr>
    </thead>
    <tbody>
      ${periodBatches.map(batch => {
        const loc = locations.find(l => l.id === batch.location_id);
        return `
          <tr>
            <td>${formatDate(batch.batch_date)}</td>
            <td>${loc?.name || 'Unknown'}</td>
            <td>${formatCurrency(batch.total_tips_collected)}</td>
            <td>${formatCurrency(batch.total_tips_allocated)}</td>
            <td>${batch.employee_count}</td>
            <td>${batch.status}</td>
          </tr>
        `;
      }).join('')}
    </tbody>
  </table>

  <h2>Adjustments</h2>
  ${relevantAdjustments.length === 0 ? '<p>No adjustments in this period.</p>' : `
    <table>
      <thead>
        <tr>
          <th>Date</th>
          <th>Type</th>
          <th>Amount</th>
          <th>Reason</th>
          <th>Approved By</th>
        </tr>
      </thead>
      <tbody>
        ${relevantAdjustments.map(adj => `
          <tr>
            <td>${formatDate(adj.created_date)}</td>
            <td>${adj.adjustment_type.replace('_', ' ')}</td>
            <td style="color: ${adj.adjustment_amount > 0 ? '#059669' : '#dc2626'}">
              ${adj.adjustment_amount > 0 ? '+' : ''}${formatCurrency(adj.adjustment_amount)}
            </td>
            <td>${adj.reason}</td>
            <td>${adj.approved_by_email}</td>
          </tr>
        `).join('')}
      </tbody>
    </table>
  `}

  <h2>Refunds & Voids</h2>
  ${refunds.length === 0 ? '<p>No refunds in this period.</p>' : `
    <div class="warning-box">
      <strong>⚠️ Refunds Detected:</strong> ${refunds.length} refunded payments found in this period.
    </div>
    <table>
      <thead>
        <tr>
          <th>Payment Date</th>
          <th>Refunded At</th>
          <th>Original Tip Amount</th>
          <th>Handling</th>
        </tr>
      </thead>
      <tbody>
        ${refunds.map(payment => `
          <tr>
            <td>${formatDate(payment.payment_date)}</td>
            <td>${payment.refunded_at ? formatDate(payment.refunded_at) : 'N/A'}</td>
            <td>${formatCurrency(payment.tip_amount)}</td>
            <td>Automatic negative adjustment created</td>
          </tr>
        `).join('')}
      </tbody>
    </table>
  `}

  <h2>Audit Event Summary</h2>
  <table>
    <thead>
      <tr>
        <th>Date</th>
        <th>Event Type</th>
        <th>Actor</th>
        <th>Summary</th>
      </tr>
    </thead>
    <tbody>
      ${relevantAuditEvents.slice(0, 50).map(event => `
        <tr>
          <td>${formatDate(event.created_date)}</td>
          <td>${event.event_type.replace('_', ' ')}</td>
          <td>${event.actor_email}</td>
          <td>${event.changes_summary || '-'}</td>
        </tr>
      `).join('')}
    </tbody>
  </table>

  <div class="footer">
    <p><strong>Declaration:</strong> This report has been generated from immutable allocation records maintained by TipFlow. 
    All allocations are cryptographically hashed and auditable. Any adjustments are approved and logged with full audit trails.</p>
    <p><strong>Report ID:</strong> ${crypto.randomUUID()}</p>
    <p><strong>Generated on:</strong> ${new Date().toISOString()}</p>
  </div>
</body>
</html>
    `;

    return Response.json({
      success: true,
      html_content: html,
      summary: {
        period_start,
        period_end,
        locations: filteredLocations.length,
        batches: periodBatches.length,
        allocations: relevantLines.length,
        adjustments: relevantAdjustments.length,
        refunds: refunds.length,
        audit_events: relevantAuditEvents.length
      }
    });

  } catch (error) {
    console.error('Generate HMRC audit pack error:', error);
    return Response.json({ success: false, error: error.message }, { status: 500 });
  }
});